# Generated by Django 3.2.4 on 2021-07-11 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20210712_0103'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='application',
        ),
        migrations.AddField(
            model_name='payout',
            name='loan',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loan'),
            preserve_default=False,
        ),
    ]
