# Generated by Django 3.2.4 on 2021-06-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
