# Generated by Django 3.2.4 on 2021-06-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_alter_charge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
