# Generated by Django 2.2.5 on 2021-06-16 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('computer_name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
