# Generated by Django 3.2.4 on 2021-06-30 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('msisdn', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15)),
                ('id_no', models.BigIntegerField()),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organisations.center')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, null=True, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='LoanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('minimum_principle', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('maximum_principle', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('loan_limit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('center', 'msisdn'), name='clients_client_unique_center_client'),
        ),
    ]
