# Generated by Django 3.2.4 on 2021-07-01 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210630_2201'),
        ('clients', '0003_auto_20210701_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
