# Generated by Django 3.2.4 on 2021-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20210702_0501'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loanprofile',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='loanprofile',
            constraint=models.UniqueConstraint(fields=('product', 'client'), name='clients_loanprofile_unique_product_client'),
        ),
    ]
