# Generated by Django 3.2.4 on 2021-07-09 23:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210630_2201'),
        ('clients', '0006_auto_20210702_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='msisdn',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.Product'),
        ),
    ]
