# Generated by Django 3.2.4 on 2021-07-10 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20210710_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_profile', to='clients.client'),
        ),
    ]
