# Generated by Django 3.2.4 on 2021-07-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_loanprofile_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprofile',
            name='auto_approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='auto_approve_ceiling',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=7),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='available_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
