# Generated by Django 3.2.4 on 2021-07-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_waived',
        ),
        migrations.AddField(
            model_name='loan',
            name='is_written_off',
            field=models.BooleanField(default=False),
        ),
    ]
