# Generated by Django 3.2.4 on 2021-07-11 17:30

from django.db import migrations, models
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20210710_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ref_no',
            field=models.CharField(default=loans.models.gen_ref_no, max_length=32),
        ),
        migrations.AddField(
            model_name='loan',
            name='ref_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
