# Generated by Django 3.2.4 on 2021-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20210711_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code',
            field=models.BigIntegerField(default=210701),
            preserve_default=False,
        ),
    ]
