# Generated by Django 3.2.4 on 2021-07-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_application_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
