# Generated by Django 3.2.4 on 2021-07-11 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0007_alter_application_reviewed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='extended',
            new_name='is_extended',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='extended_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='extended_days',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='extended_on',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='product',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='ref_no',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='waived_amount',
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='is_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ext_from', models.DateTimeField()),
                ('ext_to', models.DateTimeField()),
                ('extended_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
