# Generated by Django 3.2.4 on 2021-07-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20210712_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiver',
            old_name='created_by',
            new_name='waived_by',
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
