# Generated by Django 3.2.4 on 2021-07-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20210712_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
