# Generated by Django 3.2.4 on 2021-07-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_loan_is_disbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=8),
            preserve_default=False,
        ),
    ]
