# Generated by Django 3.2.4 on 2021-06-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20210630_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
