# Generated by Django 3.2.4 on 2021-06-30 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject header for emails ', max_length=100, null=True)),
                ('message', models.CharField(max_length=320)),
                ('priority', models.SmallIntegerField(default=3)),
                ('message_type', models.SmallIntegerField(default=1)),
                ('gateway', models.CharField(help_text='Name of SMS /email gateway', max_length=100)),
                ('message_status', models.SmallIntegerField(default=0)),
                ('delivery_response', models.CharField(max_length=100, null=True)),
                ('request_id', models.CharField(max_length=300, null=True)),
                ('sender_address', models.CharField(max_length=100, null=True)),
                ('recipient_address', models.CharField(max_length=100)),
                ('template_id', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
