# Generated by Django 3.2.4 on 2021-06-30 17:32

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=30)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, overwrite=True, populate_from=('name',), unique=True)),
                ('short_name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255, null=True)),
                ('minimum_principal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('maximum_principal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
