# Generated by Django 3.2.4 on 2021-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
